# Generated by Django 4.2.6 on 2024-04-26 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0013_rename_first_name_user_afirst_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('afirst_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('perIdentificacion', models.CharField(blank=True, db_comment='Identificacion de la persona', max_length=10, null=True, unique=True)),
                ('perNombres', models.CharField(db_comment='Nombres de la persona', max_length=70, null=True)),
                ('perApellidos', models.CharField(db_comment='Apellidos de la persona', max_length=70, null=True)),
                ('perCorreo', models.CharField(db_comment='Correo de la persona', max_length=70, unique=True)),
                ('perNumeroCelular', models.CharField(blank=True, db_comment='Numero de celular de la persona', max_length=10, null=True, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('userFoto', models.FileField(blank=True, db_comment='Foto del Usuario', null=True, upload_to='fotos/')),
                ('userTipo', models.CharField(choices=[('Asistente comercial', 'Asistente comercial'), ('Abogado', 'Abogado'), ('Administrativo', 'Administrativo')], db_comment='Nombre Tipo de usuario', max_length=20)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('fechaHoraActualizacion', models.DateTimeField(auto_now=True, db_comment='Fecha y hora última actualización')),
                ('userEstado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perIdentificacion', models.CharField(blank=True, db_comment='Identificacion de la persona', max_length=10, null=True, unique=True)),
                ('perNombres', models.CharField(db_comment='Nombres de la persona', max_length=70, null=True)),
                ('perApellidos', models.CharField(db_comment='Apellidos de la persona', max_length=70, null=True)),
                ('perCorreo', models.CharField(db_comment='Correo de la persona', max_length=70, unique=True)),
                ('perNumeroCelular', models.CharField(blank=True, db_comment='Numero de celular de la persona', max_length=10, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pqrFecha', models.DateTimeField(auto_now_add=True, db_comment='Fecha y hora del registro')),
                ('pqrDescripcion', models.TextField(db_comment='Descripcion del problema', max_length=600, null=True)),
                ('pqrRespuesta', models.TextField(blank=True, db_comment='Descripcion del problema', max_length=600, null=True)),
                ('pqrEstadoRespuesta', models.BooleanField(default=False)),
                ('pqrEstado', models.BooleanField(default=True)),
                ('pqrAbogado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pqr_abogados', to=settings.AUTH_USER_MODEL)),
                ('pqrAsistente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pqr_asistentes', to=settings.AUTH_USER_MODEL)),
                ('pqrConsumidor', models.ForeignKey(db_comment='Hace relación a la persona FK', on_delete=django.db.models.deletion.PROTECT, to='appCeibas.consumidor')),
            ],
        ),
    ]
